let tiles = {
    '11': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '12': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '13': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '14': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '15': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '16': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '21': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '22': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '23': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '24': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '25': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '26': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '31': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'e1',
    },
    '32': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '33': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '34': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '35': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '36': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '41': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'e2',
    },
    '42': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '43': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '44': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '45': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '46': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '51': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'e3',
    },
    '52': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '53': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '54': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '55': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
    '56': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'',
    },
}
let bonusTiles = {
    'e1': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'31',
    },
    'e2': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'41',
    },
    'e3': {
        title: '',
        description: '',
        img: '',
        type: 'drop',
        ref:'51',
    },
}